import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from 'react';
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  const [blogList, setBlogList] = useState([])
  
  useEffect(() => {
    async function f() {
       {
        const response = await fetch("/api/hello")
        if (response.status == 200) {
          let rs = await response.json()
          setBlogList(rs)
        }
      }
    }
    if (session) {
      f()
    }
  }, [session])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session ? (
        <>
          <p>Not signed in</p>
          <br />
          <button onClick={() => signIn()}>Sign in</button>
        </>
      ) : (
        <main className={styles.main}>
          <div className={styles.header}>
            <h4>Signed in as {session.user.name}</h4>
            <button onClick={() => signOut()}>Sign out</button>
          </div>
          <h1 className={styles.title}>My Blog</h1>
          <div className={styles.row}>
            {blogList.map(({ id, title, content }) => (
              <div className={styles.blogCardContent} key={id}>
                 <h2>{title}</h2>
                 <p>
                   {content}
                 </p>
              </div>
            ))}
          </div>
        </main>
      )}
    </div>
  );
}